SELECT * FROM EMPLOYEE;

SELECT E.*, DECODE(SUBSTR(EMP_NO,8,1),'1','남','2','여') AS GENDER
FROM EMPLOYEE E
WHERE SUBSTR(EMP_NO,8,1)='2';

SELECT * FROM JOB;
SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE JOIN DEPARTMENT ON DEPT_CODE=DEPT_ID;